### ISSUE TITLE
Delivering the Tracking Status Resource within a document (derived from splitting Issue#5)

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#11]
Following on from Issue 10, another example the logistical problems faced by organisation is the delivery and maintenance of the Tracking Status Resource at the "well known" location. Every origin would have to contain a reference (at /.well-known/dnt) to the current resource, which may have to be maintained centrally by the company's legal or data protection function.

While it is possible in the current TPE to target any URI as the declared Tracking Status Resource using a chain of HTTP Redirects, getting all a company's servers to initiate the correct server-side redirection code can be difficult.

One way to achieve this is to define a new meta element whose content attribute contains the Tracking Status Resource represented as a JSON string.

For example:
<meta name="Tracking-Status" content='{  "tracking": "N",  "compliance": [ "http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf","http://www.w3.org/TR/tracking-compliance/",   "https://www.eff.org/.well-known/dnt-policy.txt"  ], "controller": "https://baycloud.com/", "same-party": [    "cookieq.com", "baycloud.com", "consenthub.com", "cookieq.eu", "baycloud.azureedge.net",    "az417220.vo.msecnd.net"  ],  "policy": "https://baycloud.com/privacy"}' /> 

Another way would be to reference the TSR Url in an extension to the Tk response header.

Example text for TPE:

The new Tk response header is defined formally by the following ABNF

            Tk-field-name  = "TK"
            Tk-field-value = TSV [ ";" status-id] [ "%" URI-reference]
            status-id =  1*id-char
            id-char =  ALPHA / DIGIT / "_" / "-" / "+" / "=" / "/"
            URI-reference is defined as per [[RFC3986]]

For example:
Tk: C%https://corporate-site.com/.well-known/dnt

Alternatively the JSON could be quoted directly as in:
Tk: C%{  "tracking": "N",  "compliance": [ "http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf","http://www.w3.org/TR/tracking-compliance/",   "https://www.eff.org/.well-known/dnt-policy.txt"  ], "controller": "https://baycloud.com/", "same-party": [    "cookieq.com", "baycloud.com", "consenthub.com", "cookieq.eu", "baycloud.azureedge.net",    "az417220.vo.msecnd.net"  ],  "policy": "https://baycloud.com/privacy"}

An advantage of embedding the TSR in the Tk response header, either as an Uri or in JSON,
is that in future there is likely to be a standardised policy resource for an entire origin (e.g web site) where security and policy oriented headers can be declared. See the description of Origin-Policy at https://wicg.github.io/origin-policy/ .

The motivation for this is managing the "header bloat" issue arising from new recommendations such as Content-Security-Policy. It would make sense to append the Tracking Status Resource to this, and incorporating a reference inside a header is a natural way to do it. If every site must have a set of cached origin-wide resources it would be best to combine their functionality so only one extra round-trip was needed, and to minimise the size of the cache.
{
  "headers": [
    {
      "name": "Content-Security-Policy",
      "value": "script-src 'self' https://cdn.example.com",
      "type": "fallback"
    },
 {
      "name": "Tky",
      "value": "C%https://corporate-site.com/.well-known/dnt",
      "type": "fallback"
    },

Alternatively the TSR JSON could be appended to the Origin-Policy JSON within its own JSON property.

i.e. (combing the description of the Origin-Policy JSON witth the TSR:
{
  "headers": [
    {
      "name": "Content-Security-Policy",
      "value": "script-src 'self' https://cdn.example.com",
      "type": "fallback"
    },
    {
      "name": "Referrer-Policy",
      "value": "origin-when-cross-origin",
      "type": "fallback"
    }
    {
      "name": "Content-Security-Policy",
      "value": "object-src 'none'; frame-ancestors 'none'",
      "type": "baseline"
    },
    {
      "name": "Strict-Transport-Security",
      "value": "max-age=10886400; includeSubDomains; preload",
      "type": "baseline"
    },
    {
      "name": "X-Content-Type-Options",
      "value": "nosniff",
      "type": "baseline"
    }
  ],
  "cors-preflight": {
    "origins": "*"
  }
trackingStatus: {
                            "tracking": "N",
                            "compliance": [
                                "http://ec.europa.eu/justice/data-protection/article-29/documentation/opinion-recommendation/files/2012/wp194_en.pdf",
                                "http://www.w3.org/TR/tracking-compliance/",
                                "https://www.eff.org/.well-known/dnt-policy.txt"
                              ],
                            "controller": "https://baycloud.com/",
                            "same-party": [
                                  "baycloud.com",
                                  "baycloud.azureedge.net,
                              ],
                            "policy": "https://baycloud.com/privacy"
                       }
}

Whatever method is chosen, the preferred way should be the use of the well-known location. If this exists a user agent should ignore any TSR delivered by the alternative methods.

**Comment by mschunte2** [comment]
An advantage of the well-known resource is that it can be easily discovered. And that the policies are clear.
Delivering policy in bodies may lead to race conditions and may deliver policies that conflict the well-known one.

Challenge is: What can sites do if you cannot post content under the well-known resource?

**Comment by michael-oneill** [comment]
Delivering the TSR in the content for any page makes it more easy to discover, as well as more efficient because there is no reason for another roundtrip.
I would amend my proposal  by saying that if the Tk header contains a TSR (anything after and including a "{" character after the TSV is the TSR JSON), then this becomes the default value of the TSR. This fixes the problem for wordpress.com sites and similar, and allows maximum flexibility for sites to declare their policies. If a site cannot deliver a response header, it can use the http-equiv meta tag.

**Comment by michael-oneill** [comment]
On the call today we discussed using meta http-equiv tags for supplying the Tk response header, and also the difficulty some sites have implementing a TSR at the well-known location. These issues are connected because the only way to to set the {status-id} to indicate a page-specific TSR is with the Tk response. In addition, when the API is not supported, user consent (if it has been obtained) must be indicated using the out-of-band mechanism. This means that a TSV of C must be delivered either in the Tracking property of a dynamically updated TSR or in a Tk response header.
This is more than just an edge case. It is hard for large companies with multiple (first-party) sites to specify a set of common rules for a potentially legally significant TSR, especially when it must be dynamically created. Sites are often implemented on different platforms by disparate agencies and service providers, and synchronising these would be a logistic nightmare. Also, many smaller sites are often hosted by a centralised service provider that does not offer easy or standardised methods for setting response headers, or allows their customers to host their own TSRs.
My original proposal combined these issues by extending the Tk header so it could carry the URI of an independently located TSR, and allowing the header to be sent in the head section of an html document in an http-equiv tag.
This would allow a first-party site to generate its own Tk: C as well as its own page-specific TSR without the need for the {status-id} mechanism. It would still have to ensure that the “Tracking” property and TSV in the TK header were the same, leading to possible ambiguities. There would also have to be a redundant roundtrip in many circumstances just to return the TSR.
In the call Roy suggested a simpler approach which I agreed with.
This would be to not bother with the Tk header but only return the TSR JSON directly in a meta tag. There would only be one TSV (in the encoded TSR), and the whole TSR would be immediately available without needing an extra roundtrip.
Remember, this is only required in the cases that a TSR at /well-known/DNT is not available. If it is this mechanism would just be ignored. This makes the assumption that if a site can host a well-known TSR it can also generate a TK header.
This mechanism allows sites to dynamically place the following meta tag in the head section of any page that needed to comply:
<meta name=’tracking-status-resource’ content=’{“tracking”:”C”, “compliance”=” http://eur-lex.europa.eu/eprivacy-regulation”,...}’ />
This is simpler and more efficient that the last proposal, does not have the ambiguities, and fixes both use cases.

**Comment by michael-oneill** [comment]
After discussion in the last calls and considering the short timeline which means less time is available that could be spent on more important issues, I  withdraw this issue.
