### ISSUE TITLE
Different policy documents may require SAME-PARTY flag to be present, which is now an optional feature in the spec

### ISSUE THREAD

**Issue by wvholst** [w3c/dnt#2]
Having SAME-PARTY optional constitutes in fact a dependency between TPE and TPS.

**Comment by mschunte2** [comment]
Hi Walter,

what do you mean? Could you elaborate? I re-read the text and did not see a reference to the compliance spec.

Matthias

**Comment by rvaneijk** [comment]
This ties loosely in to issue # 22

**Comment by wvholst** [comment]
I wrote "in fact", not that there is a literal dependency. Given the 1st and 3rd party dichotomy, it will often be unclear to the UA which domains are part of the 1st party and which are actual 3rd parties. Any TPS is likely to have different obligations for 1st and 3rd parties while the TPS does not allow for an explicit flag indicating who is who. SAME-PARTY would allow for a (possibly too) implicit way for doing so.

**Comment by royfielding** [comment]
Presumably, a TPS (compliance specification) is binding on the parties whether or not the UA knows which are 1st and which are 3rd. In fact, it is impossible for sites to know which requests are truly first-party (as defined). At most they can state that a given resource is implemented with the expectation of being called in a first-party context, or the expectation of being called in a third-party context, or the expectation that they are a third-party context for some requests and a first-party for others. I don't think a same-party array improves on that.

BTW, note that the proposed ePR uses a _different_ definition for "third party" (based on cookie domains) than GDPR. GDPR's definition of third party is consistent with TPE's definition.

**Comment by michael-oneill** [comment]
The proposed ePR uses the definition of  “third party” in the GDPR in the main text and some recitals, but uses it in the technical (HTTP) sense when it refers to “third party cookies” in the preamble and in Recitals 23 & 24. This is one of the drafting errors that the Parliament will probably sort out.

 

I do not think it matters for this whether a subresource origin “knows” whether is being accessed at the top level or not. Walter is pointing out the real possibility that an EU compliance document might require sites to identify what declarations a site makes about the subresource domains that belong to it or its contracted data processors. It is a good thing that browsers and extensions can differentiate between those domains and others that may perhaps be there illegitimately, so the user can be made aware of them, or at least so the user agent can handle them more carefully.

 

Mike

**Comment by mschunte2** [comment]
Merge with issue 22 and clarify (Action for Rob)

**Comment by rvaneijk** [comment]
Ideally the TSR should contain information about the purpose of the interference by the first party, the person or organisation responsible for the interference, information how the end-user can withdraw his consent and all further information required based on the GDPR when personal data are collected. 

Moreover, a distinction between the first party and (sub) contractors could IMHO be made in seperate TSR-properties, i.e., one for the first party (which is the same party property), and another property listing known and trusted/contracted web resources (which would be a new web resource property).

**Comment by royfielding** [comment]
I don't see anything actionable here. I have added clarification to the policy property to encourage the reference of compliance regimes and additional requirements to the compliance property to require that it be used to list specifications that define any extensions used by a site. The identification of the data controller is already required (it defaults to the registered domain owner). Other properties that might be required in the future can be defined by a compliance regime.
