### ISSUE TITLE
Using the API to specify DNT header extensions

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#20]
Implementing site-specific consent is much easier, and more verifiable if the DNT extensions are used, as I proposed in issue 14 and https://w3c.github.io/dnt/sitespecificconsent.html

If we are not requiring UAs to implement this directly we should allow third-party libraries to offer it. This would allow innovation to be built on top of DNT, which could both help both user privacy and platform functionality. UA implementation of this could then be incorporated in a future follow-up to the TPE.

When DNT:0 is requested it should be possible to supply the rest of the header to add arbitrary further information. This could carry information that is then available to the target server, as well as client-side code operating in that origin's browsing context.

I propose a new string property for the API dictionary, "DNTVal". This contains the full header that will be sent to the requested origin (and its subresource targets if this is a site-specific call). If DNTVal is not present then the result  is a DNT:0 header as is the case now.

The first character would have to be either "1" or "0" and further characters would be removed unless the first character was "0", i.e. the further arbitrary information would only be included in a DNT: 0 header.

We do not need to specify what these extensions would be at this time, but leave the market to decide. The fact that any extra data is only allowed in the context of consent being granted will ensure this is fine from a privacy/security point of view.

This would also allow a site to specify DNT:1 to be communicated to its subresources,, and enabling DNT to be also used as a right-to-object signal (when a user had not enabled the general preference)

**Comment by royfielding** [comment]
I don't think this is useful for qualifiers. However, it would be useful to signal things like a generation (version number) for consent, or tags to indicate which of various specific consent option(s) has been given (based on the site's own consent dialog). I could see that as reducing the need for a separate cookie to track that information. Unfortunately, it could also be abused to hold a UID.

**Comment by royfielding** [comment]
I guess my comment applies more to #14

**Comment by michael-oneill** [comment]
Yes I meant arbitrary extensions rather than qualifiers, to help future innovation.

The UID issue would only be a problem for DNT:0, i.e. the user would have to give their consent to it. All characters after the first "1" would be removed if it was DNT:1

**Comment by michael-oneill** [comment]
Chris has reported interest among premium publishers in the site-specific implementation proposal in issue#14. As has been pointed out there is currently no way to signal to a server (or a client hosted browsing context) that a DNT:0 is for site-specific consent or web-wide consent. This can only be done by extending the header because relying on a javascript call does not account for non html resources. In any case we would have to design a new API to do this (the confirmSiteSpecific call cannot do it).
As we probably cannot agree on the site-specific protocol for DNT 1.0 we should at least have the ability to allow further innovation in this area, with a view to standardising something in DNT 2.0 (I think there will have to be one).
By building in a hook now (letting the API specify the DNT:0 extension) we can enable further independent work on the site-specific implementation proposal.
This also would allow European sites to efficiently signal to their (possibly US based) embedded subresources that DNT:1 rules apply, in cases where visitor have not configured a general DNT preference.
To emphasise, extensions would only be allowed when the the first character was "0", i.e. only when the user has given specific and informed consent.

**Comment by royfielding** [comment]
I think we need to redesign the API to be more browser-action oriented and then define how to influence the DNT value that one gets from calling the API.  User agents could then implement to spec and call our API as part of the fetch routine defined by the platform.
