### ISSUE TITLE
Site-specific with empty targets should apply to script-origin only

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#59]
The text says that empty array is same as null or undefined for targets. It would be better if an empty array just meant there were no targets so only the script-origin (or a subdomain of it) received DNT:0

Otherwise, if only wanted to register consent for the script origin and not any subresources, you would have to set targets to contain a non-existent subresource, or the script-origin domain., which is weird.

**Comment by royfielding** [comment]
I don't have a preference either way, as long as we can be consistent within the API. My guess is you mean the document.domain of the script's responsible document.
