### ISSUE TITLE
Changes to the JavaScript API.

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#6]
## Changes to the Javascript API

We have already discussed making the API asynchronous, here is the WebIDL  description of that plus some other enhancements I have found very useful.

The [[tracking-dnt]]] JavaScript API could be enhanced in the following ways:
-   If the `userSameParty` boolean is `true` then an exception will also be requested for any domains specified in the origin server's [[TSR](http://www.w3.org/TR/tracking-dnt#status-resource/)] `same-party` property, as long as the reciprocal `same-party` also references the origin server requesting the exception. The `domain` property will then no longer be necessary, and companies will be able to identify other main domains they manage to receive consent, other than by using the "cookie type" rules. It will also mean more efficient implementations.
- There is a new DOMString DNTVal which indicates the value of the DNT header that will be sent to this origin and the targets identified in the 'arrayOfDomainStrings' property. If it is null or absent then DNT: 0 will be sent. 
-   All functions will return a Promise to guarantee asynchronous completion when the Promise is resolved. The Promise has a TrackingStatusObject fulfilment value.
-   A TrackingStatusObject (TSO) contains a DOMString Status indicating the success or failure of the call. It MAY also contain a unique DOMString value GrantID identifying the consent instance. The GrantId will be associated in the user agent with the other information representing a consent instance, so that a proof-of-consent system can be implemented. The TSO MAY also contain a string Version identifying the current supported implementation of the API.

            partial interface Navigator {
                Promise<TrackingStatusObject> 
                    storeSiteSpecificTrackingException (TrackingPermission properties);
                Promise<TrackingStatusObject> 
                    confirmTrackingException(TrackingPermission properties);
            };
            dictionary TrackingStatusObject {
                DomString Status; // string value indicating "OK" for success or any other value for failure
                DOMString GrantId; // a unique value registered for this granted exception, 
                                   // or consent receipt. 
                                   // This can be communicated to a server so the grant  can be matched to one stored 
                                   // within the user agent for proof-of-consent purposes.
                 DOMString Version; // a string indicating what version of the API is supported by this implementation.
                                     // this is encoded as {major-version-number}.{minor-version-number}
                                    // e.g. "1.0" can signify the current version.

            };
            dictionary StoreExceptionPropertyBag {
            DOMString? domain;
            DOMString? siteName;
            DOMString? explanationString;
            DOMString? detailURI;
            DOMString? expires;
            long? maxAge;
            };
            dictionary TrackingPermission : StoreExceptionPropertyBag {
                boolean? useSameParty; // true to specify UGE is also for same-parties
                DOMString? DNTVal; // the DNT field-name to be sent in future requests to this origin server, optionally its same-parties, and any targets. 
                                   // if the property is present the first character must be either "0" or "1"
                                   // The user agent will strip any characters after the field value which defaults to "0".

            };

**Comment by npdoty** [comment]
@michael-oneill will split into multiple issues

**Comment by mschunte2** [comment]
Calling the callback means that all updates triggered by the original request for an exception have been completed. It does not guarantee that an exception has been granted.

**Comment by mschunte2** [comment]
We have to define: 
- What does a return-call on a promise mean? (e.g. I have processed your request vs. the user granted your exception)?
- Under what conditions can a party be reasonably certain that its third party are now switched from 1 to 0?

**Comment by michael-oneill** [comment]
This is done and a file with it in is in the github repo.

**Comment by mschunte2** [comment]
Conclusion: OK to return promises. Editors: Could you introduce this change to the spec? (Mike can provide more details if needed).

**Comment by michael-oneill** [comment]
Here is section 7.4 with the changes. The raw file is on the github.

 

https://w3c.github.io/dnt/dntapiwithpromises.html
