### ISSUE TITLE
User-Agent header client property information indicating support for API

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#7]
Many browsers have yet to support the JavaScript API and this makes it difficult for servers who want to register user consent to decide on whether to support the API or fall back to the out-of-band mechanism.

It is only server side code that can insert the Tk header and this is a necessity if OOBC must be used because a `Tk: C` response MUST be inserted if consent has been given.

Client-side JavaScript can be used to detect the shortfall, but this sometimes creates the necessity for another round-trip to communicate the result back to the server

Currently  even this is problematic in the case of the Microsoft Edge browser because `navigator.confirmSiteSpecificTrackingException` exists, and it is not until a call to `navigator.storeSiteSpecificTrackingException` is made,  throwing an _Access is denied_ exception, that the client code can detect that the API is not supported.

This  proposal is that browsers or browser extensions that support the API indicate this to servers by including the string `dntapi` in the User-Agent request header.

Servers or client code can easily detect this string and immediately implement the appropriate procedures.

**Comment by npdoty** [comment]
It sounds like there may be implementation bugs if the function is present but calling it throws an exception. Better to just not have the function present if it isn't going to work, so that it can be checked by JavaScript. I don't think we need to add a header or User-Agent string for this purpose.

**Comment by dwsinger** [comment]
closing as decided on the call Nov 30th 2016 (see minutes)
