### ISSUE TITLE
Revoke indication in the DNT: 1 header

### ISSUE THREAD

**Issue by michael-oneill** [w3c/dnt#8]
If tracking consent is given at a website i.e. some UI determines that the user agrees to tracking and uses the API to request the user agent grants a DNT "Exception", this could be subsequently revoked by the user within the user agent, using some browser chrome UI. When the user agent revisits the site a DNT:1 header will now be sent but the site cannot tell that this is the result of a browser based revoke. The browser may have deleted any UID cookie in the origin to enforce the user's wishes, so user agent persisted state no longer exists.

The web site UI may wish to react differently to a revoked consent than if consent had never been given, for example it may choose not to present all the information needed to inform the user of the purpose of tracking, as the user has seen it already and changed their mind.

In this case the user agent could indicated revoked consent using a qualifier to the DNT header, say "R".

e.g. DNT: 1R signals revoked consent, i.e. no tracking but the user has revoked previously given consent.

The "R" qualifier is removed after any call to the API, e.g. ConfirmSiteSpecificTrackingException.

**Comment by dwsinger** [comment]
how long/how often do I have to remember "it had dnt:0 but that was revoked"?

**Comment by mschunte2** [comment]
May be a corner case that is not worth extra effort. I put it on hold "wontfix" for now.

**Comment by dwsinger** [comment]
also, if the revocation was a result of the user saying "clean out all this remembered state", it's kind of odd to remember the state that there used to be state for this origin...

**Comment by royfielding** [comment]
I don't think it is realistic to think that a site would send less information in a consent dialog just because the user previously revoked consent. The user might have changed their mind after disliking the effect of their prior choice. Or the revocation might have been a mistaken click. In my experience, the folks asking for consent rarely believe they are at fault for a revocation.

**Comment by mschunte2** [comment]
Consensus: No urgent need. May reconsider if implementer pull.
