### ISSUE TITLE
Policy property does not indicate role of origin of respondent

### ISSUE THREAD

**Issue by wvholst** [w3c/dnt#9]
It is very likely that compliance documents will differentiate in rules for 1st and 3rd party origins of the response to any DNT:1 headers. It would make sense for such an origin to be able to indicate its stance on how it sees itself in this regard.

**Comment by npdoty** [comment]
We previously had configuration in the TSR to indicate "1" or "3" status, but the feature was removed. I believe that was partly over a concern that it wouldn't be used, and partly that it would be possible for a publisher to just indicate that they weren't tracking at all "N".

**Comment by wvholst** [comment]
This would be mostly useful for publishers to advertise that they're a 1st party  or (same party as a 1st party) and are entitled to some data collection while being able to conform to a compliance spec that allows a 1st party to indeed do so.

**Comment by michael-oneill** [comment]
The proposed eprivacy regulation calls for browsers offering the option to stop third-parties storing info. This is more than "third-party cookie blocking" but refers to the actual status as a third-party and whatever way they exfiltrate personal data i.e. not just cookies, and not just the use of "third-party" cookies:

Software placed on the market permitting electronic communications, including the
retrieval and presentation of information on the internet, shall offer the option to
prevent third parties from storing information on the terminal equipment of an enduser
or processing information already stored on that equipment [Article 10.1]

Walter's issue could be expanded to take account of this. For example the DNT header could communicate whether an HTTP request was third-party (i.e. the result of an embedded sub-resource), whether consent (DNT:0) was site specific or web wide (an important difference when it comes to cross-context tracking etc.)

**Comment by michael-oneill** [comment]
My proposal for a site-specific identifier now contains a DNT extension indicating the receiving server is an embedded third-party resource which has been given site-specific consent.

https://w3c.github.io/dnt/sitespecificconsent.html

**Comment by royfielding** [comment]
This was discussed extensively by the working group and should not be reopened unless we intend to change the definition of first party. Our definition is based on the intent of the user. There is no available mechanism for a site to determine the user's intent, so it is impossible to mechanically state that they are a first or third party for any given request. At most, they can state how the resource has been designed to be used and adjust behavior dynamically when the context is clear.

**Comment by michael-oneill** [comment]
The user's intent is indicated by their agreement to site-specific consent, or not. Or between site-specific consent and web-wide consent.

**Comment by royfielding** [comment]
What I mean is that a party (to answer Walter's question) is unable to differentiate why a request has been made. All it can do is explain what its behavior will be when it is called. In some cases, that behavior will be dynamically determined per user, including variance by cookie, Referer, and DNT value. It would be very difficult to send separate policy documents for each potential variance. Instead, what we have defined can provide both a site-wide policy (at "/.well-known/dnt/") and resource-specific policy if there is a resource-specific TSR.

I presume that a complicated site will lead to a complicated policy document, which will hopefully encourage the site designers to better separate their services.

Again, this is only the base protocol. It is possible for the compliance regimes to require additional properties be sent based on their own needs.

**Comment by mschunte2** [comment]
2017-05-01: Walter will document examples that cannot be made to work with current TPE draft.

**Comment by mschunte2** [comment]
Timeout: No input received by 2017-05-08; Closing for now. May reconsider for future release if new use cases / data.
